import {
  Anchor,
  Archive,
  ArrowRightLeft,
  ArrowUpWideNarrow,
  Bell,
  BookOpenText,
  Box,
  Boxes,
  Braces,
  CalendarClock,
  CircleArrowUp,
  CircleCheck,
  Container,
  Copy,
  CopyCheck,
  Crosshair,
  Database,
  FileCode2,
  FileKey,
  FileText,
  FolderGit2,
  FolderTree,
  Gauge,
  GitBranch,
  GitMerge,
  Globe,
  HardDrive,
  HardDriveDownload,
  HeartPulse,
  Images,
  History,
  KeyRound,
  LayoutDashboard,
  Layers,
  Library,
  Link,
  Link2,
  Lock,
  Network,
  Package,
  Puzzle,
  Radar,
  Radio,
  Rocket,
  Ruler,
  ScrollText,
  Server,
  ShieldCheck,
  ShieldEllipsis,
  ShieldHalf,
  ShieldUser,
  SlidersHorizontal,
  Split,
  Timer,
  TrendingUp,
  UserCog,
  Waypoints,
  Webhook,
  Workflow,
  type LucideIcon,
} from 'lucide-react';
import type { NavSectionId } from './catalog';

/** Lucide icon per kind key / navigator section (pure mapping, no JSX). */

export const SECTION_ICONS: Record<NavSectionId | 'pinned', LucideIcon> = {
  cluster: Server,
  workloads: Boxes,
  config: SlidersHorizontal,
  network: Network,
  storage: HardDrive,
  access: Lock,
  helm: Anchor,
  gitops: GitBranch,
  custom: Puzzle,
  pinned: Layers,
};

const KIND_ICONS: Record<string, LucideIcon> = {
  '@overview': LayoutDashboard,
  '@workloads': LayoutDashboard,
  '@resource-map': Workflow,
  '@port-forwards': ArrowRightLeft,
  '@helm': Package,
  '@access': ShieldUser,
  '@helm-charts': Library,
  '@health': HeartPulse,
  '@explain': BookOpenText,
  '@gitops': GitBranch,
  '@changes': History,
  '@netpol': Radar,
  '@upgrade': CircleArrowUp,
  nodes: Server,
  namespaces: FolderTree,
  events: Bell,
  pods: Box,
  'deployments.apps': Rocket,
  'daemonsets.apps': Layers,
  'statefulsets.apps': Database,
  'replicasets.apps': Copy,
  replicationcontrollers: CopyCheck,
  'jobs.batch': CircleCheck,
  'cronjobs.batch': CalendarClock,
  configmaps: FileText,
  secrets: KeyRound,
  resourcequotas: Gauge,
  limitranges: Ruler,
  'horizontalpodautoscalers.autoscaling': TrendingUp,
  'poddisruptionbudgets.policy': ShieldHalf,
  'priorityclasses.scheduling.k8s.io': ArrowUpWideNarrow,
  'runtimeclasses.node.k8s.io': Container,
  'leases.coordination.k8s.io': Timer,
  'mutatingwebhookconfigurations.admissionregistration.k8s.io': Webhook,
  'validatingwebhookconfigurations.admissionregistration.k8s.io': ShieldCheck,
  services: Waypoints,
  endpoints: Crosshair,
  'endpointslices.discovery.k8s.io': Split,
  'ingresses.networking.k8s.io': Globe,
  'ingressclasses.networking.k8s.io': Globe,
  'networkpolicies.networking.k8s.io': ShieldEllipsis,
  persistentvolumeclaims: HardDriveDownload,
  persistentvolumes: HardDrive,
  'storageclasses.storage.k8s.io': Archive,
  serviceaccounts: UserCog,
  'clusterroles.rbac.authorization.k8s.io': ScrollText,
  'roles.rbac.authorization.k8s.io': FileKey,
  'clusterrolebindings.rbac.authorization.k8s.io': Link2,
  'rolebindings.rbac.authorization.k8s.io': Link,
  'customresourcedefinitions.apiextensions.k8s.io': FileCode2,
  // GitOps (Argo CD, Flux).
  'applications.argoproj.io': Workflow,
  'applicationsets.argoproj.io': Layers,
  'appprojects.argoproj.io': FolderTree,
  'kustomizations.kustomize.toolkit.fluxcd.io': GitMerge,
  'helmreleases.helm.toolkit.fluxcd.io': Package,
  'gitrepositories.source.toolkit.fluxcd.io': FolderGit2,
  'ocirepositories.source.toolkit.fluxcd.io': Container,
  'helmrepositories.source.toolkit.fluxcd.io': Library,
  'helmcharts.source.toolkit.fluxcd.io': Anchor,
  'buckets.source.toolkit.fluxcd.io': Archive,
  'alerts.notification.toolkit.fluxcd.io': Bell,
  'providers.notification.toolkit.fluxcd.io': Radio,
  'receivers.notification.toolkit.fluxcd.io': Webhook,
  'imagerepositories.image.toolkit.fluxcd.io': Images,
  'imagepolicies.image.toolkit.fluxcd.io': Images,
  'imageupdateautomations.image.toolkit.fluxcd.io': Images,
};

export function kindIcon(key: string): LucideIcon {
  return KIND_ICONS[key] ?? Braces;
}
