//! Serde mirrors of the right-sizing types in `apps/desktop/src/types/index.ts`.
//!
//! CPU values are millicores, memory values bytes; `None` means "not set"
//! (current values) or "leave as is" (changes).

use serde::{Deserialize, Serialize};

use crate::cost::CostPricing;

/// Headroom, minimums and the history window of recommendations.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RightsizingSettings {
    /// Added to the CPU p95.
    pub cpu_headroom_percent: f64,
    /// Added to the memory maximum for the request.
    pub memory_headroom_percent: f64,
    /// Added to the memory maximum for the limit.
    pub memory_limit_headroom_percent: f64,
    pub min_cpu_millicores: f64,
    pub min_memory_bytes: f64,
    /// Days of Prometheus history (1–30).
    pub days: u32,
}

impl Default for RightsizingSettings {
    fn default() -> Self {
        Self {
            cpu_headroom_percent: 15.0,
            memory_headroom_percent: 20.0,
            memory_limit_headroom_percent: 40.0,
            min_cpu_millicores: 10.0,
            min_memory_bytes: 32.0 * 1024.0 * 1024.0,
            days: 7,
        }
    }
}

/// A workload by kind, namespace and name.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct WorkloadRef {
    pub kind: String,
    pub namespace: String,
    pub name: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RightsizingRequest {
    /// Namespaces to cover; empty = every namespace the user can read.
    #[serde(default)]
    pub namespaces: Vec<String>,
    /// Only this workload (details panel).
    #[serde(default)]
    pub workload: Option<WorkloadRef>,
    #[serde(default)]
    pub settings: RightsizingSettings,
    /// Recommendation strategy id (`None` = the default strategy).
    #[serde(default)]
    pub strategy: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum RightsizingSource {
    /// Days of Prometheus history.
    Prometheus,
    /// The last hour of metrics-server samples (low confidence).
    MetricsServer,
    /// No usage data at all.
    None,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Confidence {
    Low,
    Medium,
    High,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Verdict {
    /// Requests clearly above what the workload uses.
    Over,
    /// Usage above requests (memory above its request, or near its limit).
    Under,
    Balanced,
    /// No usage history.
    NoData,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Change {
    Increase,
    Decrease,
    Unchanged,
    /// Set where nothing was set.
    Set,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
pub struct ResourceValues {
    pub cpu_request: Option<f64>,
    pub cpu_limit: Option<f64>,
    pub memory_request: Option<f64>,
    pub memory_limit: Option<f64>,
}

/// Observed usage of one container (worst replica).
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
pub struct UsageStats {
    pub cpu_p95: f64,
    pub cpu_max: f64,
    pub memory_max: f64,
    /// Hours of history behind the numbers.
    pub hours: f64,
    /// Sample-weighted average CPU over the pods (`None` = unknown).
    #[serde(default)]
    pub cpu_avg: Option<f64>,
    /// Sample-weighted average working set over the pods.
    #[serde(default)]
    pub memory_avg: Option<f64>,
}

/// How a container's pods were attributed to its workload.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum EvidenceIdentity {
    /// kube-state-metrics owner series.
    #[default]
    OwnerMetrics,
    /// Pod names generated by the workload's kind (no owner series).
    NameMatch,
    /// A pod name of the window had several owners; its samples are left out.
    Ambiguous,
}

/// How much and how well usage was observed for one container.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UsageEvidence {
    /// Hours any pod of the workload was running within the window.
    pub observed_hours: f64,
    /// CPU samples ÷ running samples (at most 1; `None` = no running data).
    pub cpu_coverage: Option<f64>,
    pub memory_coverage: Option<f64>,
    pub cpu_samples: f64,
    pub memory_samples: f64,
    /// Pod names folded into the workload.
    pub pods: u32,
    /// Average running pods over the window.
    pub duty: Option<f64>,
    /// Throttled ÷ total CFS periods (`None` = too few periods).
    pub throttle_ratio: Option<f64>,
    pub oom_killed: bool,
    /// The namespace's batch was partial (failed refining queries, warnings).
    pub partial: bool,
    pub identity: EvidenceIdentity,
}

/// The resource of an HPA metric.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum HpaResource {
    Cpu,
    Memory,
    Other,
}

/// One metric an HPA scales on.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HpaMetric {
    pub resource: HpaResource,
    /// Target average utilization in % of the request (`None` = another target type).
    pub target_utilization: Option<u32>,
}

/// The HorizontalPodAutoscaler that scales a workload.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HpaInfo {
    pub name: String,
    pub min_replicas: Option<u32>,
    pub max_replicas: u32,
    pub metrics: Vec<HpaMetric>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContainerRecommendation {
    pub name: String,
    pub current: ResourceValues,
    pub recommended: ResourceValues,
    pub usage: Option<UsageStats>,
    pub cpu: Change,
    pub memory: Change,
    pub memory_limit: Change,
    pub cpu_limit: Change,
    /// The strategy's confidence in this container's numbers.
    pub confidence: Confidence,
    /// Caveats of the strategy and of the limit adjustment.
    pub warnings: Vec<RecommendationWarning>,
    /// The CPU limit rose with the request (current limit ÷ request ratio kept).
    pub cpu_limit_raised: bool,
    /// The memory limit rose with the request (current limit ÷ request ratio kept).
    pub memory_limit_raised: bool,
}

/// A caveat of a recommendation. `code` is a stable kebab-case id the UI
/// translates (unknown codes of newer strategies fall back to `detail`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RecommendationWarning {
    pub code: String,
    pub detail: Option<String>,
}

impl RecommendationWarning {
    pub fn new(code: &str) -> Self {
        Self {
            code: code.to_string(),
            detail: None,
        }
    }

    pub fn with_detail(code: &str, detail: impl Into<String>) -> Self {
        Self {
            code: code.to_string(),
            detail: Some(detail.into()),
        }
    }
}

/// A recommendation strategy the backend offers.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RightsizingStrategyInfo {
    /// Stable id (`percentile-headroom`).
    pub id: String,
    /// Display name in English (product names stay as they are).
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WorkloadRecommendation {
    pub kind: String,
    pub namespace: String,
    pub name: String,
    pub uid: String,
    pub replicas: u32,
    pub confidence: Confidence,
    pub verdict: Verdict,
    /// Hours of history (per replica) behind the recommendation.
    pub coverage_hours: f64,
    pub containers: Vec<ContainerRecommendation>,
    /// Recommended − current requests per month for all replicas
    /// (negative = saving), in the report currency.
    pub monthly_delta: f64,
    /// Current requests per month for all replicas.
    pub monthly_current: f64,
    /// At least one value would change.
    pub changed: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RightsizingReport {
    pub source: RightsizingSource,
    /// History the numbers cover.
    pub window_secs: u64,
    pub settings: RightsizingSettings,
    pub currency: String,
    /// Price model of `monthly_delta` (the cluster's estimate prices).
    pub pricing: CostPricing,
    /// Largest saving first, then largest increase.
    pub workloads: Vec<WorkloadRecommendation>,
    /// Conditions worth telling the user (translated by the UI).
    pub notes: Vec<RightsizingNote>,
    /// Id of the strategy that produced the recommendations.
    pub strategy: String,
    /// Every strategy the backend offers.
    pub strategies: Vec<RightsizingStrategyInfo>,
    pub computed_at: i64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum RightsizingNoteKind {
    /// Prometheus failed; the metrics-server hour is used instead.
    PrometheusFailed,
    /// Neither Prometheus nor metrics-server history is available.
    NoUsage,
    /// Pods could not be listed for the metrics-server fallback.
    PodsUnavailable,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RightsizingNote {
    pub kind: RightsizingNoteKind,
    pub detail: Option<String>,
}

/// New resource values of one container (`None` = unchanged).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContainerResourceChange {
    pub container: String,
    #[serde(default)]
    pub cpu_request: Option<f64>,
    #[serde(default)]
    pub cpu_limit: Option<f64>,
    #[serde(default)]
    pub memory_request: Option<f64>,
    #[serde(default)]
    pub memory_limit: Option<f64>,
}
